process.on('uncaughtException',e=>console.log('UNCAUGHT:',e.message));
const {JSDOM}=require('jsdom');const fs=require('fs');
const file=__dirname+'/../edge-lab/strategy-lab.html',csv=__dirname+'/fixtures/edge.csv';const alerts=[];
const w=new JSDOM(fs.readFileSync(file,'utf8'),{runScripts:'dangerously',pretendToBeVisual:true,beforeParse(w){w.HTMLCanvasElement.prototype.getContext=()=>new Proxy({},{get:()=>()=>{}});w.alert=m=>alerts.push(m);w.confirm=()=>true;w.Element.prototype.scrollIntoView=()=>{}}}).window,d=w.document,$=i=>d.getElementById(i);
const sleep=t=>new Promise(r=>setTimeout(r,t)),txt=i=>$(i).textContent.replace(/\s+/g,' ').trim();
(async()=>{await sleep(400);
 $('poolOn').checked=true;$('poolOn').dispatchEvent(new w.Event('change'));console.log('U1 pool toggle refused while empty:',!$('poolOn').checked,'|',alerts.pop());
 $('loadBundled').click();$('poolName').value='BTC';$('poolAdd').click();
 $('poolName').value='BTC2';$('poolAdd').click();console.log('U2 same dataset twice refused:',alerts.pop());
 $('csv').value=fs.readFileSync(csv,'utf8');$('loadCsv').click();$('poolName').value='ALT';$('poolAdd').click();
 $('poolOn').checked=true;$('poolOn').dispatchEvent(new w.Event('change'));console.log('U3 pool info:',txt('poolInfo'));
 $('note').value='pooled trend test';$('strat').value='ma';$('strat').dispatchEvent(new w.Event('change'));$('runSweep').click();await sleep(30000);
 console.log('U4 pooled verdict:',txt('verdict').slice(0,150));
 console.log('U5 evaluated label:',(txt('resStats').match(/sweep winner[^E]*/)||['?'])[0].trim());
 console.log('U6 register entry:',(d.querySelector('#hypList table tbody tr')||{textContent:'none'}).textContent.replace(/\s+/g,' ').slice(0,120));
 console.log('U7 header effective count:',txt('cN'));
 $('poolOn').checked=false;$('poolOn').dispatchEvent(new w.Event('change'));$('loadBundled').click();$('run').click();await sleep(1500);
 console.log('U8 single BTC run after pooled sweep:',txt('verdict').slice(0,120));
 $('poolClear').click();$('genData').click();$('poolName').value='SYN';$('poolAdd').click();$('loadBundled').click();$('poolName').value='BTC';$('poolAdd').click();
 console.log('U9 synthetic + dated pool refused:',alerts.pop());
 $('poolClear').click();const before=txt('cN');$('genData').click();$('poolName').value='S1';$('poolAdd').click();$('genData').click();$('poolName').value='S2';$('poolAdd').click();
 $('poolOn').checked=true;$('poolOn').dispatchEvent(new w.Event('change'));$('strat').value='brk';$('strat').dispatchEvent(new w.Event('change'));$('runSweep').click();await sleep(4000);
 console.log('U10 synthetic pool is practice: header before/after',before,'/',txt('cN'),'| entry:',(d.querySelector('#hypList table tbody tr')||{textContent:''}).textContent.replace(/\s+/g,' ').slice(0,70));
 console.log('alerts left:',alerts.length?alerts:'none');process.exit(0)})();
