const assert=require('node:assert/strict'),crypto=require('crypto'),fs=require('fs'),L=require('./research_core.js');
let count=0;async function test(name,f){await f();console.log('PASS',name);count++}
const envelope=JSON.parse(fs.readFileSync(__dirname+'/../../research/LOCKED-PROTOCOL.json')),P=envelope.protocol;
const now=Date.parse('2026-09-23T00:06:00Z')/1000,day=86400,end=Math.floor(now/day)*day;
const candles=(start,until)=>Array.from({length:(until-start)/day},(_,i)=>{const px=100+i*.2;return {start:String(start+i*day),open:String(px),high:String(px+.4),low:String(px-.2),close:String(px+.1),volume:'1000'}});
(async()=>{
 await test('SHA256 matches platform implementation across ASCII, Unicode and block boundaries',()=>{for(const s of ['', 'abc','BTC 🚀 café',...Array.from({length:140},(_,i)=>'x'.repeat(i)),'a'.repeat(10000)])assert.equal(L.sha256Text(s),crypto.createHash('sha256').update(s).digest('hex'))});
 await test('frozen protocol checksum and future window',()=>{assert.equal(L.sha256Text(L.canonicalJSON(P)),envelope.sha256);assert.ok(Date.parse(P.startInclusive)>Date.parse(P.lockedAt));assert.equal(P.hypotheses.length,2);assert.equal(P.riskPolicy.liveTradingEnabled,false)});
 await test('closed daily candles only; duplicate conflicts, gaps and staleness fail closed',()=>{
  const c=candles(end-200*day,end);const result=L.normalizeCandles({candles:[...c,...candles(end,end+day)]},now);assert.equal(result.bars.length,200);assert.equal(result.incomplete,1);
  assert.throws(()=>L.normalizeCandles({candles:[...c,{...c[0],close:'100.2'}]},now),/Conflicting/);
  assert.throws(()=>L.normalizeCandles({candles:c.filter((_,i)=>i!==70)},now),/Missing/);
  assert.throws(()=>L.normalizeCandles({candles:c.slice(0,-1)},now),/Latest/);
  assert.throws(()=>L.normalizeCandles({candles:c.map((v,i)=>i===2?{...v,high:'0'}:v)},now),/OHLC/);
 });
 await test('strict products: USD spot only, duplicates removed, unavailable not zero',()=>{const a={product_id:'BTC-USD',product_type:'SPOT',quote_currency_id:'USD',price:'100',volume_24h:'20',price_percentage_change_24h:'9.43%'};const r=L.marketRows([a,a,{...a,product_id:'ETH-EUR',quote_currency_id:'EUR'},{...a,product_id:'BTC-FUT-USD',product_type:'FUTURE'},{...a,product_id:'SOL-USD',price:'',volume_24h:null}]);assert.equal(r.length,2);assert.equal(r[0].volumeUSD,2000);assert.equal(r[0].change24h,9.43);assert.equal(r[1].price,null);assert.equal(r[1].volumeUSD,null)});
 await test('locked rules reproduce causal legacy signals on a fixed synthetic anchor',()=>{const C=require('./core.js'),b=L.normalizeCandles({candles:candles(end-200*day,end)},now).bars,r=L.lockedSignals(b);for(const h of P.hypotheses){const sig=C.signal(b,h.strategy,h.params),item=r.find(x=>x.id===h.id);assert.equal(item.on,!!sig.at(-1));assert.equal(item.previous,!!sig.at(-2))}});
 await test('dollar risk boundaries including high-water pause',()=>{const p=P.riskPolicy;assert.equal(L.experimentRisk(5000,5000,p).stage,'WITHIN_LIMITS');assert.equal(L.experimentRisk(4500,5000,p).stage,'REVIEW');assert.equal(L.experimentRisk(4500,5000,p).riskFraction,.0025);assert.equal(L.experimentRisk(4250,5000,p).newRiskAllowed,false);assert.equal(L.experimentRisk(4000,5000,p).stage,'HALT');assert.equal(L.experimentRisk(6500,7500,p).stage,'HALT');assert.throws(()=>L.experimentRisk(5000,4000,p))});
 await test('range overlap ignores label and venue; touching exclusive ends do not overlap',()=>{const a={asset:'BTC',start:'2020-01-01',end:'2021-01-01'};assert.equal(L.overlapsExposure(a,{...a,start:'2020-06-01'}),true);assert.equal(L.overlapsExposure(a,{...a,start:'2021-01-01',end:'2022-01-01'}),false);assert.equal(L.overlapsExposure(a,{...a,asset:'ETH'}),false);assert.equal(L.overlapsExposure(a,{...a,asset:'UNKNOWN'}),true)});
 await test('bounded retries and no credentials',async()=>{let calls=0;const data=await L.fetchPublicJSON('/market/products',async(url,opts)=>{assert.equal(opts.credentials,'omit');assert.equal(opts.method,'GET');assert.ok(!opts.headers.Authorization);calls++;return calls<3?{ok:false,status:429}:{ok:true,status:200,json:async()=>({products:[]})}},async()=>{});assert.equal(calls,3);assert.deepEqual(data,{products:[]});calls=0;await assert.rejects(()=>L.fetchPublicJSON('/market/products',async()=>{calls++;return {ok:false,status:503}},async()=>{}),/three/);assert.equal(calls,3);await assert.rejects(()=>L.fetchPublicJSON('/orders',()=>{}),/public/) });
 await test('one scan paginates, preserves fixed BTC anchor and isolates context assets',async()=>{const paths=[];const result=await L.collectMarketScan(async path=>{paths.push(path);const u=new URL('https://unit.test'+path);if(u.pathname==='/market/products')return {products:[]};return {candles:candles(+u.searchParams.get('start'),+u.searchParams.get('end')+1)}},now,()=>{},P);assert.equal(result.complete,true);assert.equal(result.details.length,3);assert.equal(result.details[0].start,P.warmupStartInclusive.slice(0,10));assert.equal(result.details[0].bars,201);assert.equal(result.details[1].bars,200);assert.equal(result.details[1].signals.length,0);assert.equal(paths.length,5);assert.ok(paths.every(p=>!p.includes('orders')))});
 await test('partial candle failure cannot masquerade as complete',async()=>{const result=await L.collectMarketScan(async path=>{if(path==='/market/products?product_type=SPOT&limit=100&offset=0')return {products:[]};throw Error('provider unavailable')},now,()=>{},P);assert.equal(result.complete,false);assert.equal(result.details.length,0);assert.equal(result.errors.length,3)});
 await test('repeated product pages stop instead of infinite pagination',async()=>{const rows=Array.from({length:100},(_,i)=>({product_id:'X'+i+'-USD'}));await assert.rejects(()=>L.collectMarketScan(async()=>({products:rows}),now),/repeated/)});
 await test('listing stops when Coinbase ignores the limit or flags the last page',async()=>{
  const all=Array.from({length:250},(_,i)=>({product_id:'X'+i+'-USD',product_type:'SPOT',quote_currency_id:'USD',price:'1',volume_24h:'1'}));
  const pages=[];const r=await L.collectMarketScan(async path=>{const u=new URL('https://unit.test'+path);if(u.pathname==='/market/products'){pages.push(path);return {products:all}}return {candles:candles(+u.searchParams.get('start'),+u.searchParams.get('end')+1)}},now,()=>{},P);
  assert.equal(pages.length,1);assert.equal(r.rows.length,250);assert.equal(r.truncated,false);
  const hundred=all.slice(0,100);pages.length=0;const r2=await L.collectMarketScan(async path=>{const u=new URL('https://unit.test'+path);if(u.pathname==='/market/products'){pages.push(path);return {products:hundred,pagination:{has_next:false}}}return {candles:candles(+u.searchParams.get('start'),+u.searchParams.get('end')+1)}},now,()=>{},P);
  assert.equal(pages.length,1);assert.equal(r2.rows.length,100)});
 console.log(count+' v7 market/research assertion groups passed. No live data.');
})().catch(e=>{console.error(e);process.exitCode=1});
